### ISSUE TITLE
Correct (?) API usage triggers log message "api_password is going to deprecate" 

### ISSUE THREAD

**Issue by sabeechen** [home-assistant/hassio#1071]
**Home Assistant release with the issue:**
HA 0.92.2

**Operating environment (HassOS/Generic):**
HassOS 2.11

**Supervisor logs:**
N/A

**Description of problem:**
I've [authored an addon](https://github.com/sabeechen/hassio-google-drive-backup) that uses the hassio proxy to Home Assistant to update sensor state.  As advised in the [docs](https://developers.home-assistant.io/docs/en/hassio_addon_communication.html), I provide it with an HTTP header of the form:
`Authorization: Bearer %HASSIO_TOKEN%`

Which authenticates successfully, but I and [some of my users](https://github.com/sabeechen/hassio-google-drive-backup/issues/33) can see in the Home Assistant logs:
`api_password is going to deprecate. You need to use a bearer token to access /api/states/sensor.snapshot_backup from 172.30.32.2`

Am I using the Hass.io API correctly?  I'm passing in a header with the bearer token, so presumably Hassio is translating that back into using an API password somewhere.  I'm concerned that my add-on will stop working in a future update.  I've tried fixing this by:
* Adding and removing api_password from my configuration.yaml
* Sending headers `X-Ha-Access: %HASSIO_TOKEN%` instead, which I learned from [reading this part of Hass.io source](https://github.com/home-assistant/hassio/blob/6970cebf80d25d1dde297a443909c6a22d06a281/hassio/api/proxy.py#L30).  This authenticates as well, but still prints the error message.

**configuration.yaml**
```yaml
homeassistant:
  name: Home
  latitude: #removed
  longitude: #removed
  elevation: #removed
  unit_system: imperial
  time_zone: #removed
  customize: !include customize.yaml
  
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
http:
  base_url: #removed
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
default_config:
discovery:
conversation:
history:
recorder:
  purge_keep_days: 1
owntracks:
  max_gps_accuracy: 100
```
