### ISSUE TITLE
Unable to find service mqtt/publish

### ISSUE THREAD

**Issue by pratham2003** [home-assistant/hassio#122]
Hass.io version : 0.50.0

Trigger screenshot
https://cdn.discordapp.com/attachments/330990055533576204/341457402811514880/unknown.png

Action screenshot
https://cdn.discordapp.com/attachments/330990055533576204/341457451939266561/unknown.png

Generated in automations.yaml
```
- action:
  - data:
      payload: Test message from HA
      qos: 0
      retain: 0
      topic: mirror-led
    service: mqtt.publish
  alias: Mirror LED - CW
  id: '1501445972178'
  trigger:
  - above: '0'
    below: '100'
    entity_id: input_slider.led_mirror_cw
    platform: numeric_state
```

The automation doesn't trigger when I move the input slider.
The input slider is defined in configuration.yaml

```
input_slider:
  - led_mirror_cw:
      name: Cool White
      initial: 50
      min: 0
      max: 100
      step: 1
  - led_mirror_ww:
      name: Warm White
      initial: 50
      min: 0
      max: 100
      step: 1
```

But on manually triggering the automation the error in `hassio homeassistant logs` is as follows
```
2017-07-31 11:25:20 WARNING (MainThread) [homeassistant.core] Unable to find service mqtt/publish
```
