### ISSUE TITLE
Cannot access hass.io panel from remote

### ISSUE THREAD

**Issue by ggravlingen** [home-assistant/hassio#147]
Hi,

I setup a hass.io-instance on a raspberry pi zero w at home and everything worked fine and dandy. Move the raspberry to an off-site location and I can no longer access the hass.io-panel. The log console throws a bunch of the errors below. What could be the cause if this? Is the panel running on its own port?

![image](https://user-images.githubusercontent.com/21142447/29205561-f42576b2-7e7d-11e7-9b64-49a66cf1be15.png)

The panel sits there just fine in the side bar:
![image](https://user-images.githubusercontent.com/21142447/29205575-0673c364-7e7e-11e7-8a9a-6f4454434abd.png)

Extract of the config:
```
homeassistant:
  name: abc
  latitude: 12.34
  longitude: 12.34
  elevation: 10
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include_dir_merge_named extraconfig/customize
  packages: !include_dir_named extraconfig/packages


config:
frontend:
hassio:
discovery:


http:
  api_password: !secret http_password


panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include extraconfig/standalonefiles/floorplan.yaml


panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://x.ddns.net:3218
```
