### ISSUE TITLE
New Customization in 0.53 throws erroneous warning

### ISSUE THREAD

**Issue by JSCSJSCS** [home-assistant/hassio#185]
Just tried out the new Customization feature of Hass.io 0.53 and it threw a warning, while actually doing what was expected. After clicking SAVE to change the default name of a camera.usps.mail entity, the change was made to the customize.yaml file and it worked as expected. 

![customization warning](https://user-images.githubusercontent.com/656601/30283763-d378deb4-96cd-11e7-8922-83c43fbf1c02.png)

I have the following in my configuration.yaml file:

```
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 701
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
```
And after making the edit with the Customize function, the customize.yaml file was updated as expected:

```
camera.usps_mail:
  friendly_name: USPS Mail Images
```
So it appears that my configuration.yaml file DOES properly include customize.yaml and my changes did take effect despite the warning to the contrary.

![settings](https://user-images.githubusercontent.com/656601/30284109-e2087c40-96ce-11e7-8672-53d89bf5582b.png)

Love this feature by the way. Hope the issue can be rectified easily.
