### ISSUE TITLE
New automation not showing up since .58.1

### ISSUE THREAD

**Issue by phairplay** [home-assistant/hassio#268]
Hi since installing. 58.1 I'm unable to get new automation to show up in the state section. I can edit but not add.

I'm adding them directly to the yaml file

**Comment by arsaboo** [comment]
Not sure what you mean by `I can edit but not add`. Are you not seeing your automations in the entity tab? Please provide more details, including an example of automation that is not working.

**Comment by phairplay** [comment]
Sorry 
I did add this originally.

I'm not able to see anything in the Development tab, I've logged in via putty and used the command prompts to check my config files and everything is okay, yet when I restart or even reboot. no new automation shows up.
`- alias: Qnap Status
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.phairserver_status
    from: 'good'
    to: 'warning'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.qnap`

**Comment by arsaboo** [comment]
For automations to appear in the configuration, you need `id: `. Plus, you have `hide_entity: true` which will hide the automation.

**Comment by phairplay** [comment]
Still not showing up

```
- id: my_unique_id
- alias: Qnap Status
  trigger:
    platform: state
    entity_id: sensor.phairserver_status
    to: 'bad'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.qnap
```

**Comment by arsaboo** [comment]
```
- id: my_unique_id
  alias: Qnap Status
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.phairserver_status
    to: 'bad'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.qnap
```
