### ISSUE TITLE
Watchdog miss API response problem

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/hassio#340]
It's been a few versions (can't recall) that hassio won't work with normal container restarts for homeassistant. I seem to always end up in doing a cold reboot. 

I've been triggering now a normal update from 0.62.0 to 0.62.1 and I get the below:

```
# hassio s logs

Error decoding json invalid character '\x1b' looking for beginning of value: 18-01-31 18:12:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 18:17:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 18:22:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 18:27:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 18:32:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 18:37:42 INFO (MainThread) [hassio.updater] Fetch update data from https://raw.githubusercontent.com/home-assistant/hassio/master/version.json
18-01-31 18:37:42 INFO (MainThread) [hassio.addons.git] Pull addon https://github.com/bestlibre/hassio-addons repository
18-01-31 18:37:42 INFO (MainThread) [hassio.addons.git] Pull addon https://github.com/home-assistant/hassio-addons repository
18-01-31 18:37:43 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/git/53caca22/base_debian/config.json: required key not provided @ data['boot']. Got None
required key not provided @ data['startup']. Got None
18-01-31 18:37:43 INFO (MainThread) [hassio.addons] Load addons: 34 all - 0 new - 0 remove
18-01-31 18:37:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 18:42:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 18:47:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 18:52:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 18:57:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 19:02:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 19:07:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 19:12:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 19:17:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 19:22:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 19:27:46 WARNING (MainThread) [hassio.homeassistant] Home-Assistant API config missmatch
18-01-31 19:31:20 INFO (SyncWorker_6) [hassio.docker.interface] Update docker 0.62.0 with homeassistant/raspberrypi3-homeassistant:0.62.1
18-01-31 19:31:20 INFO (SyncWorker_6) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag 0.62.1.
18-01-31 19:33:37 INFO (SyncWorker_6) [hassio.docker.interface] Tag image homeassistant/raspberrypi3-homeassistant with version 0.62.1 as latest
18-01-31 19:33:37 INFO (SyncWorker_6) [hassio.docker.interface] Stop homeassistant/raspberrypi3-homeassistant docker application
18-01-31 19:34:08 INFO (SyncWorker_6) [hassio.docker.interface] Clean homeassistant/raspberrypi3-homeassistant docker application
18-01-31 19:34:08 INFO (SyncWorker_6) [hassio.docker.interface] Cleanup docker images: ['homeassistant/raspberrypi3-homeassistant:0.62.0']
18-01-31 19:34:18 INFO (SyncWorker_10) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.62.1
18-01-31 19:37:46 WARNING (MainThread) [hassio.tasks] Watchdog miss API response from Home-Assistant
18-01-31 19:42:46 ERROR (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant API!
18-01-31 19:42:46 INFO (SyncWorker_9) [hassio.docker.interface] Restart homeassistant/raspberrypi3-homeassistant
18-01-31 19:47:46 WARNING (MainThread) [hassio.tasks] Watchdog miss API response from Home-Assistant

```

**Comment by pvizeli** [comment]
Yes, please don't interact with docker commands to a hass.io managed container. Use our cli with `hassio ha restart/stop/start`

"Home-Assistant API config missmatch" mean a wrong home-assistant http config. Can you post your home-assistant config?

**Comment by ciotlosm** [comment]
I've not used docker commands. I just hit the "Update" button displayed on the Hassio panel above addons. 

I'm using nginx (from bestlibre) in front of home-assistant, so that might influence things.

My config:
```
core-ssh:/config# cat configuration.yaml 
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: !secret home_timezone
  unit_system: metric
  packages: !include_dir_named packages
  customize_domain: !include customize_domain.yaml
  customize_glob: !include customize_glob.yaml
group: !include groups.yaml
```


```
core-ssh:/config# cat packages/core.yaml 
```

```
...
http:
  api_password: !secret http_password 
  trusted_networks:
    - ::1
    - 192.168.0.0/24
  server_port: 8123
  ip_ban_enabled: true
  login_attempts_threshold: 4
...
```
