### ISSUE TITLE
Xiaomi miio still broken in 0.63

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/hassio#356]
As per:-
https://github.com/home-assistant/home-assistant/issues/12298

Construct still not updated

**Comment by syssi** [comment]
Can somebody help here? The xiaomi_miio components requires a recent version (0.3.5) of python-miio plus construct>=2.9.23 (defined at the setup.py of python-miio). The stack trace (https://github.com/home-assistant/home-assistant/issues/12298#issuecomment-364798570) of affected users reveals the required construct version isn't used / wasn't updated.

The issue can be fixed temporary(?) by: https://github.com/home-assistant/home-assistant/issues/12028#issuecomment-364794947

```
docker exec homeassistant pip3 install construct==2.9.29
```

What' the root cause for this issue? Are there other components requiring a old version of construct? A fresh virtualenv installation isn't affected. An existing virtualenv installation updates the requirements, too. Just hassio users are in trouble.

**Comment by syssi** [comment]
@DavidFW1960 has a hassio install which sticks to construct 2.8.10: https://community.home-assistant.io/t/miio-platform-broken-after-upgrade-0-62/41118/52

**Comment by syssi** [comment]
A hassio build installs a lot of stuff:  https://github.com/home-assistant/hassio-build/blob/master/homeassistant/generic/Dockerfile

There are conflicting packages probably!

**Comment by syssi** [comment]
I found the root cause. It's another component (homeassistant.components.sensor.eddystone_temperature) which depends on beacontools which is pinned to construct==2.8.10.

**Comment by citruz** [comment]
I am the creator of eddystone_temperature and beacontools. Will update the package as soon as possible, in the next days.

**Comment by syssi** [comment]
Awesome! Let me know if you need support!

**Comment by pvizeli** [comment]
Yeah, Hass.io install all requerements with pip and that can ends in a problem like this. But since 1.2 years of hass.io it was the first time we run into a problem like this...

**Comment by htcheroportugal** [comment]
syssi so, how can we solve the problem with xiaomi vaccum?

**Comment by pvizeli** [comment]
@htcheroportugal downgrade your Home-Assistant and wait until the fix from @citruz is inside Home-Assistant

**Comment by kiwijunglist** [comment]
I joined hass Io after the bug. What version should I downgrade too. Thanks.

**Comment by AlexandrePautet** [comment]
I downgraded to 0.61.1 and the xiaomi_miio module is working

I'm on hassio, I rollback to 0.61.1 from 0.62 using :
curl -d '{"version": "0.61.1"}' http://hassio/homeassistant/update

https://community.home-assistant.io/t/miio-platform-broken-after-upgrade-0-62/41118/2

**Comment by pvizeli** [comment]
you can also use `hassio homeassistant update -o version=0.61.1`

**Comment by kiwijunglist** [comment]
Thanks. Roll back to v 0.61.1 worked for me. My yeelight bulbs, Xiaomi Phillips bulbs and xiaomi air filter are working. I wait patiently for v 0.64 fix.  Thanks for everyone's hard work.

**Comment by pejotigrek** [comment]
update 0.63.3 fixed xiaomi vacuum issues on my hass.io installation

**Comment by pejotigrek** [comment]
...aaaand it was too soon to be happy. vacuum stopped working :(

device is online, but even then I've got:

- 2018-02-19 21:57:23 WARNING (SyncWorker_8) [miio.device] Retrying with incremented id, retries left: 3
- 2018-02-19 21:57:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.rosita_jetson is taking over 10 seconds
- 2018-02-19 21:57:28 ERROR (SyncWorker_8) [miio.device] Got error when receiving: timed out
- 2018-02-19 21:57:28 WARNING (SyncWorker_8) [miio.device] Retrying with incremented id, retries left: 2
- 2018-02-19 21:57:34 ERROR (SyncWorker_8) [miio.device] Got error when receiving: timed out
- 2018-02-19 21:57:34 WARNING (SyncWorker_8) [miio.device] Retrying with incremented id, retries left: 1
- 2018-02-19 21:57:39 ERROR (SyncWorker_8) [miio.device] Got error when receiving: timed out
- 2018-02-19 21:57:39 WARNING (SyncWorker_8) [homeassistant.components.vacuum.xiaomi_miio] Got exception while fetching the state: No response from the device

in the logs..
don't want to downgrade, will wait for the next update..

**Comment by syssi** [comment]
Please enable the debug output by

```
logger:                                                                                                                                                                                                                                                                                                                                                                   
  default: warn                                                                                                                                                                                                                                                                                                                                                           
  logs:                                                                                                                                                                                                                                                                                                                                                                   
    homeassistant.components.light.xiaomi_miio: debug                                                                                                                                                                                                                                                                                                                     
    homeassistant.components.fan.xiaomi_miio: debug                                                                                                                                                                                                                                                                                                                       
    homeassistant.components.vacuum.xiaomi_miio: debug                                                                                                                                                                                                                                                                                                                       
    homeassistant.components.light.xiaomi_miio: debug                                                                                                                                                                                                                                                                                                                       
    miio: debug    
```

Restart HA and provide the content of the homeassistant.log again please!
