### ISSUE TITLE
Unable to find service zwave/set_config_parameter

### ISSUE THREAD

**Issue by hink** [home-assistant/hassio#359]
Version 0.63.1

Error when restarting HA

>  Warning: Unable to find service zwave/set_config_parameter

```yaml
- alias: Kitchen Switch Load Status
  trigger:
    platform: state
    entity_id: light.kitchen_canlights_level
  action:
    service: zwave.set_config_parameter
    data_template: 
      { 
        "node_id": 4,
        "parameter": 21,
        "value": "Blue"
      }
```
