### ISSUE TITLE
Cannot Download Snapshots from UI

### ISSUE THREAD

**Issue by ericvandamme** [home-assistant/hassio#675]
Since upgrading to 77.1, downloads of snapshots fail.

Stated reason by Chrome is that it needs authorization.

![capture](https://user-images.githubusercontent.com/28657401/44890833-3cd7e600-acaa-11e8-9543-8a7d8df16146.PNG)

**Comment by cogneato** [comment]
Same here.
![image](https://user-images.githubusercontent.com/2456810/44891802-86bacf00-ac9e-11e8-9ee0-48fd2cd2185b.png)

**Comment by theaquarium** [comment]
Can confirm that this is still a bug on 0.77.2. Seems to be an issue with users as users on 0.76 would cause the same problem.

**Comment by theaquarium** [comment]
Yes, but if you have disabled API password, it won't work.

**Comment by robin13** [comment]
+1 - having same issue and with this config (non-relevant bits removed)
```
homeassistant:
  auth_providers:
   - type: homeassistant

http:
  #api_password: !secret http_password
```
even the manual replacement of a password does not work
