### ISSUE TITLE
Invalid token for access

### ISSUE THREAD

**Issue by ryanmboyce** [home-assistant/hassio#741]
I am receiving the following error when trying to run an add-on that worked just fine a few days ago and I didn't make any changes. 

```
- id: '165237682817201'
  alias: Backup Service
  trigger:
  - at: '15:10:00'
    platform: time
  action:
  - data:
      addon: ce20243c_remote_backup
    service: hassio.addon_start
```
Error on the supervisor:
`18-10-05 22:13:54 INFO (SyncWorker_11) [hassio.docker.interface] Clean fixated/remote-backup-armhf Docker application
18-10-05 22:13:56 INFO (SyncWorker_11) [hassio.docker.addon] Start Docker add-on fixated/remote-backup-armhf with version 0.3.0
18-10-05 22:13:56 WARNING (MainThread) [hassio.api.security] /snapshots/new/full no role for ce20243c_remote_backup
18-10-05 22:13:56 ERROR (MainThread) [hassio.api.security] Invalid token for access /snapshots/new/full`

Doesn't matter if I try running it manually, still doesn't work. Any ideas?
